openapi: 3.1.0
info:
  title: LexML API
  description: Busca legislação, jurisprudência e doutrina via LexML SRU API.
  version: "1.0.0"
servers:
  - url: https://api.vercel.app
paths:
  /api/status:
    get:
      summary: Verifica se a API está ativa
      responses:
        '200':
          description: OK
  /api/search:
    get:
      summary: Busca no acervo do LexML
      parameters:
        - name: query
          in: query
          required: true
          schema: { type: string }
        - name: start
          in: query
          required: false
          schema: { type: integer, default: 1 }
        - name: max
          in: query
          required: false
          schema: { type: integer, default: 10 }
      responses:
        '200':
          description: Resultados da busca em JSON
