openapi: 3.1.0
info:
  title: API Proxy DataJud
  description: Consulta jurisprudência e processos no CNJ DataJud
  version: "1.0.0"
servers:
  - url: https://api-qp5181vqi-lets-boras-projects.vercel.app
paths:
  /api/status:
    get:
      summary: Healthcheck da API
      responses:
        '200':
          description: API online
  /api/datajud:
    get:
      summary: Consulta processos/jurisprudência no DataJud CNJ
      parameters:
        - name: tribunal
          in: query
          required: false
          schema: { type: string }
        - name: classe
          in: query
          required: false
          schema: { type: string }
        - name: assunto
          in: query
          required: false
          schema: { type: string }
        - name: pagina
          in: query
          required: false
          schema: { type: integer, default: 1 }
      responses:
        '200':
          description: Retorno do DataJud em JSON
